-- MySQL Script generated by MySQL Workbench
-- Sun Jan 11 17:27:25 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineeri
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema repositoriov3
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema repositoriov3
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `repositoriov3` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `repositoriov3` ;

-- -----------------------------------------------------
-- Table `repositoriov3`.`t_administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_administradores` (
  `id_admin` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombre_usuario` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `contrasena` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombre` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `apellidos` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `dni` CHAR(8) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `ultimo_acceso` TIMESTAMP NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT '1',
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_admin`),
  UNIQUE INDEX `uk_nombre_usuario` (`nombre_usuario` ASC) VISIBLE,
  UNIQUE INDEX `uk_email` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uk_dni` (`dni` ASC) VISIBLE,
  INDEX `idx_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_solicitudes` (
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo_solicitud` ENUM('estudiante', 'docente') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombres` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellidos` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dni` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `numero_contacto` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `escuela_profesional` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `acepta_terminos` TINYINT(1) NULL DEFAULT '0',
  `formato_ajustado` TINYINT(1) NULL DEFAULT '0',
  `errores_leidos` TINYINT(1) NULL DEFAULT '0',
  `tramite_informado` TINYINT(1) NULL DEFAULT '0',
  `declara_verdad` TINYINT(1) NULL DEFAULT '0',
  `nombre_proyecto` VARCHAR(300) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `observaciones` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `link_tesis_publicada` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `estado` ENUM('pendiente', 'en_revision', 'aprobado', 'observado', 'requiere_correccion', 'publicado') NOT NULL,
  `fecha_solicitud` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `tipo_financiamiento` ENUM('publico', 'autofinanciado') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `idx_dni` (`dni` ASC) VISIBLE,
  INDEX `idx_estado` (`estado` ASC) VISIBLE,
  INDEX `idx_fecha` (`fecha_solicitud` ASC) VISIBLE,
  INDEX `idx_estado_fecha` (`estado` ASC, `fecha_solicitud` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_asesores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_asesores` (
  `id_asesor` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `orden_asesor` ENUM('primero', 'segundo') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellidos_nombres` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dni` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `orcid` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_asesor`),
  INDEX `idx_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_asesores_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_auditoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_auditoria` (
  `id_auditoria` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tabla_afectada` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_registro` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo_operacion` ENUM('INSERT', 'UPDATE', 'DELETE') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `usuario_id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `datos_anteriores` JSON NULL DEFAULT NULL,
  `datos_nuevos` JSON NULL DEFAULT NULL,
  `ip_address` VARCHAR(45) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fecha_operacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_auditoria`),
  INDEX `idx_tabla` (`tabla_afectada` ASC) VISIBLE,
  INDEX `idx_fecha` (`fecha_operacion` ASC) VISIBLE,
  INDEX `idx_usuario` (`usuario_id` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_autores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_autores` (
  `id_autor` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `orden_autor` ENUM('principal', 'segundo', 'tercero', 'coautor') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo_colaborador` ENUM('autor', 'colaborador_interno', 'colaborador_externo') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT 'autor',
  `tipo_ubicacion` ENUM('interno', 'externo') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `tipo_rol` ENUM('estudiante', 'docente') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `rol` ENUM('estudiante', 'docente') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `nombres` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellidos` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dni` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `url_orcid` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `escuela_profesional` VARCHAR(150) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_autor`),
  INDEX `idx_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_autores_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_coautores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_coautores` (
  `id_coautor` CHAR(36) NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo_ubicacion` ENUM('interno', 'externo') NOT NULL,
  `tipo_rol` ENUM('estudiante', 'docente') NOT NULL,
  `nombres` VARCHAR(120) NOT NULL,
  `apellidos` VARCHAR(120) NOT NULL,
  `orcid_url` VARCHAR(50) NULL DEFAULT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_coautor`),
  INDEX `idx_coautores_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_coautores_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_codigo_verificacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_codigo_verificacion` (
  `id_codigo_verificacion` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `email` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `codigo` CHAR(6) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `usado` TINYINT(1) NULL DEFAULT NULL,
  `expira_en` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_codigo_verificacion`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_documentos` (
  `id_documento` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo_documento` ENUM('hoja_autorizacion', 'constancia_empastado', 'tesis_pdf', 'constancia_originalidad', 'documento_investigacion', 'reporte_similitud', 'informe_investigacion') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `nombre_archivo` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ruta_archivo` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tamano_kb` INT NULL DEFAULT NULL,
  `fecha_subida` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente', 'aprobado', 'observado') NOT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `razon_rechazo` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fecha_revision` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_documento`),
  INDEX `idx_solicitud` (`id_solicitud` ASC) VISIBLE,
  INDEX `idx_tipo` (`tipo_documento` ASC) VISIBLE,
  INDEX `idx_solicitud_tipo` (`id_solicitud` ASC, `tipo_documento` ASC) VISIBLE,
  CONSTRAINT `fk_documentos_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_historial_solicitudes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_historial_solicitudes` (
  `id_historial` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_documento` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `id_admin` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `estado_anterior` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `estado_nuevo` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `comentario` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fecha_cambio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `file_path_historico` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`id_historial`),
  INDEX `idx_solicitud` (`id_solicitud` ASC) VISIBLE,
  INDEX `idx_admin` (`id_admin` ASC) VISIBLE,
  INDEX `idx_fecha` (`fecha_cambio` ASC) VISIBLE,
  INDEX `idx_solicitud_fecha` (`id_solicitud` ASC, `fecha_cambio` ASC) VISIBLE,
  INDEX `idx_documento` (`id_documento` ASC) VISIBLE,
  INDEX `idx_historial_id` (`id_historial` ASC) VISIBLE,
  INDEX `idx_historial_id_historial` (`id_historial` ASC) VISIBLE,
  CONSTRAINT `fk_historial_admin`
    FOREIGN KEY (`id_admin`)
    REFERENCES `repositoriov3`.`t_administradores` (`id_admin`)
    ON DELETE SET NULL,
  CONSTRAINT `fk_historial_documento`
    FOREIGN KEY (`id_documento`)
    REFERENCES `repositoriov3`.`t_documentos` (`id_documento`)
    ON DELETE CASCADE,
  CONSTRAINT `fk_historial_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_documentos_imagenes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_documentos_imagenes` (
  `id_imagen` INT NOT NULL AUTO_INCREMENT,
  `id_documento` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `ruta_imagen` VARCHAR(500) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `nombre_archivo` VARCHAR(255) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `created_at` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `history_id` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  PRIMARY KEY (`id_imagen`),
  INDEX `id_documento` (`id_documento` ASC) VISIBLE,
  INDEX `idx_docimg_history` (`history_id` ASC) VISIBLE,
  INDEX `idx_docimg_history_id` (`history_id` ASC) VISIBLE,
  CONSTRAINT `fk_docimg_history`
    FOREIGN KEY (`history_id`)
    REFERENCES `repositoriov3`.`t_historial_solicitudes` (`id_historial`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `t_documentos_imagenes_ibfk_1`
    FOREIGN KEY (`id_documento`)
    REFERENCES `repositoriov3`.`t_documentos` (`id_documento`)
    ON DELETE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 31
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_historial_rechazos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_historial_rechazos` (
  `id_historial` INT NOT NULL AUTO_INCREMENT,
  `id_documento` VARCHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `estado` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `razon_rechazo` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `fecha_registro` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_historial`),
  INDEX `idx_documento` (`id_documento` ASC) VISIBLE,
  INDEX `idx_fecha` (`fecha_registro` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 89
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_jurados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_jurados` (
  `id_jurado` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `rol_jurado` ENUM('presidente', 'primer_miembro', 'segundo_miembro') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `apellidos_nombres` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `dni` VARCHAR(20) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `orcid` VARCHAR(50) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_jurado`),
  INDEX `idx_solicitud` (`id_solicitud` ASC) VISIBLE,
  CONSTRAINT `fk_jurados_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `repositoriov3`.`t_notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `repositoriov3`.`t_notificaciones` (
  `id_notificacion` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `id_solicitud` CHAR(36) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `tipo_notificacion` ENUM('recepcion', 'aprobacion', 'rechazo', 'correccion', 'recordatorio') CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NOT NULL,
  `destinatario_email` VARCHAR(100) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `asunto` VARCHAR(200) CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `contenido` TEXT CHARACTER SET 'utf8mb4' COLLATE 'utf8mb4_unicode_ci' NULL DEFAULT NULL,
  `enviado` TINYINT(1) NULL DEFAULT '0',
  `fecha_envio` TIMESTAMP NULL DEFAULT NULL,
  `fecha_creacion` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `created_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_notificacion`),
  INDEX `idx_solicitud` (`id_solicitud` ASC) VISIBLE,
  INDEX `idx_enviado` (`enviado` ASC) VISIBLE,
  INDEX `idx_email` (`destinatario_email` ASC) VISIBLE,
  CONSTRAINT `fk_notificaciones_solicitud`
    FOREIGN KEY (`id_solicitud`)
    REFERENCES `repositoriov3`.`t_solicitudes` (`id_solicitud`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
